---
sudo: required
language: python
services:
  - docker
before_install:
  - sudo apt-get -qq update
install:
  - pip install yamllint pre-commit
script:
  - yamllint .
  - pre-commit run --all-files
